version: "1.0"

services:
  app:
    build: ./
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine3.20
    env_file:
      - .env
    ports:
      - 5432:5432


  nginx:
   image: nginx
   container_name: nginx
   ports:
     - "8080:8080"
   volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
   depends_on:
     - app
